services:
  frontend:
    image: pills_parser-frontend
    container_name: pills_parser_frontend
    networks:
      - app-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always

networks:
    app-network:
      external: true